trigger:
  branches:
    include:
      - main  # Change this if you want other branches to trigger the pipeline

pool:
  vmImage: 'ubuntu-latest'  # Microsoft-hosted agent with Java 17 & Maven pre-installed

variables:
  JAVA_VERSION: '17'
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2  # Caches Maven dependencies

stages:
  - stage: Build_and_Test
    displayName: 'Build and Test'
    jobs:
      - job: Build
        displayName: 'Build and Test with Maven'
        steps:
          - task: Cache@2
            displayName: 'Cache Maven Dependencies'
            inputs:
              key: 'maven | "$(Agent.OS)" | **/pom.xml'
              restoreKeys: 'maven | "$(Agent.OS)"'
              path: $(MAVEN_CACHE_FOLDER)

          - task: JavaToolInstaller@0
            displayName: 'Set up Java 17'
            inputs:
              versionSpec: $(JAVA_VERSION)
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'preInstalled'

          - script: |
              mvn clean install -DskipTests
            displayName: 'Build Project'

          - script: |
              mvn test -Dspring.datasource.url=jdbc:h2:mem:testdb \
                       -Dspring.datasource.driver-class-name=org.h2.Driver \
                       -Dspring.datasource.username=sa \
                       -Dspring.datasource.password= \
                       -Dspring.sql.init.mode=never
            displayName: 'Run Unit Tests with H2'

          - task: PublishTestResults@2
            displayName: 'Publish Test Results'
            inputs:
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              testRunTitle: 'Maven Unit Tests'

          - task: CopyFiles@2
            displayName: 'Copy JAR for Artifacts'
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)/lootbox-service/target'
              Contents: '*.jar'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish JAR Artifact'
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'drop'
