name: CI Pipeline

on:
  push:
    branches:
      - main  # Runs the pipeline when pushing to the main branch
  pull_request:
    branches:
      - main  # Runs the pipeline on pull requests to main

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest  # You can change this to self-hosted if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Alternative: 'zulu', 'adopt', 'corretto'
          java-version: '17'
          cache: 'maven'

      - name: Build Project
        run: |
          cd lootbox-service
          mvn clean install -DskipTests

      - name: Run Unit Tests with H2
        run: |
          cd lootbox-service
          mvn test -Dspring.datasource.url=jdbc:h2:mem:testdb \
                   -Dspring.datasource.driver-class-name=org.h2.Driver \
                   -Dspring.datasource.username=sa \
                   -Dspring.datasource.password= \
                   -Dspring.sql.init.mode=never

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports
          path: lootbox-service/target/surefire-reports/
          retention-days: 7

      - name: Upload Built JAR
        uses: actions/upload-artifact@v3
        with:
          name: lootbox-service-jar
          path: lootbox-service/target/*.jar
          retention-days: 7
