name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Define JAVA_HOME (Fix for OWASP Dependency-Check)
        run: echo "JAVA_HOME=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.14-7/x64" >> $GITHUB_ENV

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Build Project
        run: |
          cd lootbox-service
          mvn clean install -DskipTests

      - name: Run Unit Tests with H2
        run: |
          cd lootbox-service
          mvn test -Dspring.datasource.url=jdbc:h2:mem:testdb \
                   -Dspring.datasource.driver-class-name=org.h2.Driver \
                   -Dspring.datasource.username=sa \
                   -Dspring.datasource.password= \
                   -Dspring.sql.init.mode=never

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: lootbox-service/target/surefire-reports/
          retention-days: 7

  static-analysis:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run SpotBugs Static Code Analysis
        run: |
          cd lootbox-service
          mvn com.github.spotbugs:spotbugs-maven-plugin:spotbugs

      - name: Upload SpotBugs Report
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report
          path: lootbox-service/target/spotbugsXml.xml

  security-check:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Define JAVA_HOME (Fix for OWASP Dependency-Check)
        run: echo "JAVA_HOME=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.14-7/x64" >> $GITHUB_ENV

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "lootbox-service"
          path: "lootbox-service"
          format: "HTML"

      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: lootbox-service/dependency-check-report.html

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: [build-and-test, static-analysis, security-check]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/lootbox-service:latest ./lootbox-service

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/lootbox-service:latest
