name: CI Pipeline

on:
  push:
    branches:
      - main  # Runs on pushes to main
  pull_request:
    branches:
      - main  # Runs on pull requests to main

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use GitHub-hosted Linux runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  
          java-version: '17'

      - name: Build and Run Tests
        run: |
          cd lootbox-service
          mvn clean install
